### ISSUE TITLE
Banner image too big?

### ISSUE THREAD

**Issue by datawookie** [satRdays/johannesburg2019#3]
The banner image takes a long time to load. How big is it? We need to make it smaller because the site looks nasty while the image is loading.

**Comment by datawookie** [comment]
@Axiematic can you please take a look at this? Thanks!

**Comment by Axiematic** [comment]
On it!

**Comment by stephlocke** [comment]
We've also been doing some work on changing this particular bit of code to default load the image through the html not through the js as this makes the performance pretty poor. @DaveParr did we get Steve's changes in the end and did we implement them in the hugo template?

**Comment by Axiematic** [comment]
@stephlocke that's great! Looking forward to implementing the changes :).

**Comment by Axiematic** [comment]
@DataWookie should we close this issue?

**Comment by datawookie** [comment]
Sure thing.

**Comment by stephlocke** [comment]
Some optimisations of the code are:
1. JS improvements https://github.com/satRdays/hugo-satrdays-theme/blob/master/static/js/trianglewave.js
2. Async call https://github.com/satRdays/hugo-satrdays-theme/blob/master/layouts/partials/footer.html#L32
3. Offload image to main html/csss to enable caching https://github.com/satRdays/hugo-satrdays-theme/blob/master/static/css/satrday.css#L21

**Comment by datawookie** [comment]
Thanks, @stephlocke!
